### ISSUE TITLE
Composer install Issue

### ISSUE THREAD

**Issue by mecmec98** [markheramis/laravel-restful-api#46]
Deprecation Notices

```
Deprecation Notice: Using ${var} in strings is deprecated, use {$var} instead in /usr/share/php/Symfony/Component/Console/Command/DumpCompletionCommand.php:48
Deprecation Notice: Using ${var} in strings is deprecated, use {$var} instead in /usr/share/php/Symfony/Component/Console/Command/DumpCompletionCommand.php:56
Deprecation Notice: Using ${var} in strings is deprecated, use {$var} instead in /usr/share/php/Composer/Autoload/AutoloadGenerator.php:879
Deprecation Notice: Using ${var} in strings is deprecated, use {$var} instead in /usr/share/php/Composer/Autoload/AutoloadGenerator.php:884
No composer.lock file present. Updating dependencies to latest instead of installing from lock file. See https://getcomposer.org/install for more information.
```

Php Fatal Error
```
PHP Fatal error:  Uncaught Error: Class "Normalizer" not found in /usr/share/php/Symfony/Component/String/AbstractUnicodeString.php:31
Stack trace:
#0 /usr/share/php/Symfony/Component/Console/Helper/ProgressBar.php(383): Symfony\Component\Console\Helper\Helper::width()
#1 /usr/share/php/Symfony/Component/Console/Helper/ProgressBar.php(322): Symfony\Component\Console\Helper\ProgressBar->setMaxSteps()
#2 /usr/share/php/Composer/Util/Loop.php(89): Symfony\Component\Console\Helper\ProgressBar->start()
#3 /usr/share/php/Composer/Installer/InstallationManager.php(497): Composer\Util\Loop->wait()
#4 /usr/share/php/Composer/Installer/InstallationManager.php(362): Composer\Installer\InstallationManager->waitOnPromises()
#5 /usr/share/php/Composer/Installer/InstallationManager.php(282): Composer\Installer\InstallationManager->downloadAndExecuteBatch()
#6 /usr/share/php/Composer/Installer.php(754): Composer\Installer\InstallationManager->execute()
#7 /usr/share/php/Composer/Installer.php(583): Composer\Installer->doInstall()
#8 /usr/share/php/Composer/Installer.php(279): Composer\Installer->doUpdate()
#9 /usr/share/php/Composer/Command/InstallCommand.php(139): Composer\Installer->run()
#10 /usr/share/php/Symfony/Component/Console/Command/Command.php(298): Composer\Command\InstallCommand->execute()
#11 /usr/share/php/Symfony/Component/Console/Application.php(1015): Symfony\Component\Console\Command\Command->run()
#12 /usr/share/php/Symfony/Component/Console/Application.php(299): Symfony\Component\Console\Application->doRunCommand()
#13 /usr/share/php/Composer/Console/Application.php(336): Symfony\Component\Console\Application->doRun()
#14 /usr/share/php/Symfony/Component/Console/Application.php(171): Composer\Console\Application->doRun()
#15 /usr/share/php/Composer/Console/Application.php(131): Symfony\Component\Console\Application->run()
#16 /usr/bin/composer(84): Composer\Console\Application->run()
#17 {main}
  thrown in /usr/share/php/Symfony/Component/String/AbstractUnicodeString.php on line 31

Fatal error: Uncaught Error: Class "Normalizer" not found in /usr/share/php/Symfony/Component/String/AbstractUnicodeString.php:31
Stack trace:
#0 /usr/share/php/Symfony/Component/Console/Helper/ProgressBar.php(383): Symfony\Component\Console\Helper\Helper::width()
#1 /usr/share/php/Symfony/Component/Console/Helper/ProgressBar.php(322): Symfony\Component\Console\Helper\ProgressBar->setMaxSteps()
#2 /usr/share/php/Composer/Util/Loop.php(89): Symfony\Component\Console\Helper\ProgressBar->start()
#3 /usr/share/php/Composer/Installer/InstallationManager.php(497): Composer\Util\Loop->wait()
#4 /usr/share/php/Composer/Installer/InstallationManager.php(362): Composer\Installer\InstallationManager->waitOnPromises()
#5 /usr/share/php/Composer/Installer/InstallationManager.php(282): Composer\Installer\InstallationManager->downloadAndExecuteBatch()
#6 /usr/share/php/Composer/Installer.php(754): Composer\Installer\InstallationManager->execute()
#7 /usr/share/php/Composer/Installer.php(583): Composer\Installer->doInstall()
#8 /usr/share/php/Composer/Installer.php(279): Composer\Installer->doUpdate()
#9 /usr/share/php/Composer/Command/InstallCommand.php(139): Composer\Installer->run()
#10 /usr/share/php/Symfony/Component/Console/Command/Command.php(298): Composer\Command\InstallCommand->execute()
#11 /usr/share/php/Symfony/Component/Console/Application.php(1015): Symfony\Component\Console\Command\Command->run()
#12 /usr/share/php/Symfony/Component/Console/Application.php(299): Symfony\Component\Console\Application->doRunCommand()
#13 /usr/share/php/Composer/Console/Application.php(336): Symfony\Component\Console\Application->doRun()
#14 /usr/share/php/Symfony/Component/Console/Application.php(171): Composer\Console\Application->doRun()
#15 /usr/share/php/Composer/Console/Application.php(131): Symfony\Component\Console\Application->run()
#16 /usr/bin/composer(84): Composer\Console\Application->run()
#17 {main}
  thrown in /usr/share/php/Symfony/Component/String/AbstractUnicodeString.php on line 31
```

**Comment by markheramis** [comment]
You are missing php8.2-intl

try running

```
sudo apt install php8.2-intl
```

also you might wanna install the other php packages as well

try doing

```
sudo apt install php8.2-curl php8.2-mysql php8.2-mbstring php8.2-zip php8.2-intl php8.2-redis php8.2-xml php8.2-cli
```

and you might wanna include `php8.2-dev` and `php8.2-xdebug` if you're in a development machine. That'll come in handy.
